### ISSUE TITLE
Google is not  rendering when we use deterministic js

### ISSUE THREAD

**Issue by bebef1987** [dpalmeiro/firefox-perf-tools#1]
https://github.com/dpalmeiro/firefox-perf-tools/blob/a6b2b621692a640a5beb74578eee4aa54d99437f/replay/mitmproxy/scripts/inject.py#L29

Tested this and it looks like google is not rendering when using the deterministic JS

@dpalmeiro is there a reason we use the first <script> tag?
WPR is using the first <head>  
https://github.com/catapult-project/catapult/blob/master/web_page_replay_go/src/webpagereplay/transformers.go#L286

Tested with the first</head> and all works as expected

**Comment by dpalmeiro** [comment]
I just wanted to make sure I inject it before any JS activity starts.  However, if injecting after head is working then that may be the better approach.  Thanks for noticing this.
